name: regions-music
version: 1.0.2
summary: Music App
description: An app to play music according to your location

confinement: strict
base: core18
grade: stable

slots:
  dbus-regions-music:
    interface: dbus
    bus: session
    name: org.bsm.bhc.regions-music

architectures:
  - amd64

apps:
  regions-music:
    command: regions_music
    extensions: [flutter-master]
    plugs:
    - network
    - system-observe
    - process-control
    slots:
      - dbus-regions-music
parts:
  regions-music:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
    stage-packages:
    - libsqlite3-dev
