name: Analyze and test

on:
    push:
        branches: ["dev-ci/cd"]
    pull_request:
        branches: ["master", "develop"]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: dart-lang/setup-dart@v1

            - name: Install dependencies
              run: flutter pub get

            - name: Analyze project source
              run: flutter analyze --fatal-infos

            - name: Run tests
              run: flutter test
