name: CI/CD Pipeline

on:
    push:
        branches: ["dev-ci/cd"]
    pull_request:
        branches: ["master", "develop"]

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.0

            - name: Install dependencies
              run: flutter pub get

            - run: dart run build_runner build

            - name: Analyze project source
              run: flutter analyze --fatal-infos

            - name: Run tests
              run: flutter test

    build_linux:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.0

            - name: Install dependencies
              run: flutter pub get

            - run: dart run build_runner build

            - run: |
                  sudo apt-get update -y
                  sudo apt-get install -y ninja-build libgtk-3-dev

            - name: Build
              run: flutter build linux

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: regions_music_linux
                  path: build/linux/
                  if-no-files-found: error

    build_web:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.0

            - name: Install dependencies
              run: flutter pub get

            - run: dart run build_runner build

            - run: flutter config --enable-web

            - name: Build
              run: flutter build web

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: regions_music_web
                  path: build/web/
                  if-no-files-found: error

    build_android:
        runs-on: ubuntu-latest
        needs: test

        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.0

            - name: Install dependencies
              run: flutter pub get

            - run: dart run build_runner build

            - run: flutter config --enable-android

            - name: Build
              run: flutter build apk

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: regions_music_android
                  path: build/
                  if-no-files-found: error

    build_windows:
        runs-on: windows-latest
        needs: test

        steps:
            - uses: actions/checkout@v4

            - uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.19.0

            - name: Install dependencies
              run: flutter pub get

            - run: dart run build_runner build

            - run: flutter config --enable-windows-desktop

            - name: Build
              run: flutter build windows

            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: regions_music_windows
                  path: build/windows/
                  if-no-files-found: error
